[versions]

androidCompileSdk = "34"

androidGradlePlugin = "8.7.1"
kotlin = "1.9.25"

[libraries]

androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.6"

kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1"
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.1"
cash-turbine = "app.cash.turbine:turbine:1.1.0"

junit = "junit:junit:4.13.2"
androidx-test-ext-junit = "androidx.test.ext:junit:1.2.1"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.6.1"

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
